"""exalted

Revision ID: 28a856f45c2a
Revises: 34c052edb7e9
Create Date: 2020-01-21 16:46:12.795779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a856f45c2a'
down_revision = '34c052edb7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_boutiques_category'), 'boutiques', ['category'], unique=False)
    op.create_index(op.f('ix_boutiques_postal_code'), 'boutiques', ['postal_code'], unique=False)
    op.create_index(op.f('ix_boutiques_reviews'), 'boutiques', ['reviews'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boutiques_reviews'), table_name='boutiques')
    op.drop_index(op.f('ix_boutiques_postal_code'), table_name='boutiques')
    op.drop_index(op.f('ix_boutiques_category'), table_name='boutiques')
    # ### end Alembic commands ###
